################################################
# Server configurations
################################################
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080


################################################
# Application (global) configurations
################################################
application:
    # License path
    # Absolute path to GroupDocs license file
    licensePath: 'Licenses/GroupDocs.Metadata.NET.lic'

################################################
# Common configurations
################################################
common:
  # File rewriting on document uploading
  # Set false to keep both files
  # Set true to replace files with same name
  rewrite: true
  # Document download
  # Set false to disable document download
  download: true
  # Document upload
  # Set false to disable document upload
  upload: true
  # File browser
  # Set false to disable document browse
  browse: true

################################################
# GroupDocs.Metadata configurations
################################################
metadata:
  # Files directory path
  # Absolute path to files directory
  filesDirectory: 'DocumentSamples/Metadata'
  # Default document
  # Absolute path to default document
  defaultDocument: ''
  # Pages preload
  # How many pages from a document should be loaded, remaining pages will be loaded on page scrolling
  # Set 0 to load all pages at once
  preloadPageCount: 0
  # HTML rendering mode
  # Set false for image mode
  # Set true for HTML mode
  htmlMode: true
  # Using cache
  # Set true to enable cache
  cache: true